In [72]:
import pandas as pd
import numpy as np 
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report

In [8]:
df= pd.read_csv('spam.csv', encoding= "latin1")

In [9]:
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [11]:
df.v1.value_counts()

v1
ham     4825
spam     747
Name: count, dtype: int64

In [26]:
df.pop('Unnamed: 4')

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
       ...
5567    NaN
5568    NaN
5569    NaN
5570    NaN
5571    NaN
Name: Unnamed: 4, Length: 5572, dtype: str

In [27]:
df.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [29]:
df.v1.value_counts()/len(df)*100

v1
ham     86.593683
spam    13.406317
Name: count, dtype: float64

In [32]:
df['spam']= df['v1'].apply(lambda x: 1 if x=='spam' else 0)

In [33]:
df.head()

     v1                                                 v2  spam
0   ham  Go until jurong point, crazy.. Available only ...     0
1   ham                      Ok lar... Joking wif u oni...     0
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3   ham  U dun say so early hor... U c already then say...     0
4   ham  Nah I don't think he goes to usf, he lives aro...     0

In [34]:
df.shape

(5572, 3)

Train Test split

In [39]:
x_train, x_test, y_train, y_test =train_test_split(df.v2, df.spam,test_size=0.2)

In [40]:
x_test.shape

(1115,)

In [42]:
x_train[: 4]

979     Another month. I need chocolate weed and alcohol.
3014     &lt;#&gt;  mins but i had to stop somewhere f...
3259    I'm always looking for an excuse to be in the ...
1743                     I love to wine and dine my lady!
Name: v2, dtype: str

In [43]:
y_train[:4]

979     0
3014    0
3259    0
1743    0
Name: spam, dtype: int64

Create bag of words representation using CountVectorizer

In [85]:
v=CountVectorizer()
x_train_cv=v.fit_transform(x_train.values)
#x_test_cv=v.transform(x_test)

In [48]:
x_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59553 stored elements and shape (4457, 7767)>

In [49]:
x_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0], shape=(7767,))

In [50]:
x_train_cv.shape

(4457, 7767)

In [80]:
v.get_feature_names_out()

array(['00', '000', '000pes', ..., 'ûªve', 'ûò', 'ûówell'],
      shape=(7767,), dtype=object)

In [56]:
v.vocabulary_

{'another': 988,
 'month': 4591,
 'need': 4745,
 'chocolate': 1824,
 'weed': 7450,
 'and': 970,
 'alcohol': 907,
 'lt': 4265,
 'gt': 3281,
 'mins': 4516,
 'but': 1594,
 'had': 3312,
 'to': 6944,
 'stop': 6504,
 'somewhere': 6319,
 'first': 2904,
 'always': 941,
 'looking': 4216,
 'for': 2969,
 'an': 966,
 'excuse': 2731,
 'be': 1287,
 'in': 3659,
 'the': 6832,
 'city': 1841,
 'love': 4243,
 'wine': 7540,
 'dine': 2357,
 'my': 4682,
 'lady': 4010,
 '10': 258,
 'min': 4503,
 'later': 4045,
 'yeah': 7688,
 'that': 6827,
 'what': 7487,
 'thought': 6877,
 'lemme': 4091,
 'know': 3979,
 'if': 3624,
 'anything': 1010,
 'goin': 3192,
 'on': 4951,
 'life': 4118,
 'means': 4434,
 'lot': 4231,
 'me': 4427,
 'not': 4845,
 'because': 1296,
 'people': 5156,
 'world': 7609,
 'calls': 1640,
 'them': 6840,
 'friends': 3036,
 'call': 1626,
 'ge': 3120,
 'none': 4827,
 'nowhere': 4861,
 'ikno': 3632,
 'doesdiscount': 2417,
 'shitinnit': 6106,
 'ic': 3603,
 'there': 6845,
 'are': 1059,
 'lotta': 4235,
 'childporn': 1808,
 'cars': 1693,
 'then': 6843,
 'worry': 7614,
 'sure': 6633,
 'you': 7713,
 'll': 4178,
 'get': 3141,
 'it': 3772,
 'urgent': 7213,
 'your': 7717,
 'mobile': 4559,
 'no': 4811,
 'was': 7403,
 'awarded': 1185,
 '000': 1,
 'bonus': 1438,
 'caller': 1634,
 'prize': 5430,
 '02': 7,
 '09': 154,
 '03': 13,
 'this': 6867,
 'is': 3760,
 'our': 5025,
 '2nd': 402,
 'attempt': 1142,
 'contact': 2002,
 '0871': 91,
 '872': 695,
 '9755': 732,
 'box95qu': 1485,
 'hi': 3448,
 'we': 7430,
 'have': 3378,
 'now': 4858,
 'moved': 4618,
 'in2': 3660,
 'pub': 5491,
 'would': 7622,
 'great': 3255,
 'cud': 2130,
 'come': 1929,
 'up': 7193,
 'wonder': 7589,
 'cos': 2043,
 'dun': 2517,
 'rem': 5689,
 'seeing': 5991,
 'silver': 6173,
 'car': 1672,
 'thk': 6868,
 'saw': 5934,
 'black': 1389,
 'one': 4957,
 'secret': 5982,
 'admirer': 828,
 'reveal': 5767,
 'who': 7507,
 'thinks': 6862,
 'so': 6294,
 'special': 6372,
 '09065174042': 218,
 'opt': 4986,
 'out': 5027,
 'reply': 5719,
 '50': 531,
 'per': 5158,
 'msg': 4631,
 'recd': 5631,
 'cust': 2148,
 'care': 1677,
 '07821230901': 37,
 'much': 4649,
 'just': 3893,
 'some': 6307,
 'textin': 6808,
 'how': 3545,
 'bout': 1468,
 'meeting': 4446,
 'at': 1131,
 'received': 5636,
 'content': 2005,
 'enjoy': 2632,
 'hello': 3419,
 've': 7268,
 'got': 3222,
 'of': 4911,
 'bath': 1263,
 'do': 2406,
 'hair': 3318,
 'when': 7493,
 'done': 2441,
 'long': 4209,
 'fuckin': 3058,
 'showr': 6141,
 'sorry': 6339,
 'takes': 6705,
 'little': 4169,
 'time': 6911,
 'child': 1806,
 'afraid': 855,
 'dark': 2189,
 'become': 1298,
 'teenager': 6760,
 'wants': 7393,
 'stay': 6467,
 'all': 918,
 'night': 4791,
 'jokin': 3863,
 'oni': 4959,
 'lar': 4033,
 'ìï': 7758,
 'busy': 1593,
 'wun': 7651,
 'disturb': 2390,
 'ì_': 7755,
 'jus': 3892,
 'finish': 2891,
 'blowing': 1416,
 'dinner': 2361,
 'already': 931,
 'shuhui': 6149,
 'say': 5935,
 'change': 1744,
 'suntec': 6617,
 'steamboat': 6478,
 'noe': 4815,
 'where': 7497,
 'nights': 4794,
 'nt': 4865,
 'staying': 6470,
 'port': 5322,
 'step': 6480,
 'liao': 4109,
 'too': 6980,
 'ex': 2721,
 'seems': 5996,
 'unnecessarily': 7181,
 'hostile': 3531,
 'won': 7586,
 'tkts': 6931,
 'euro2004': 2685,
 'cup': 2140,
 'final': 2880,
 'or': 4992,
 '800': 635,
 'cash': 1697,
 'collect': 1914,
 '09058099801': 184,
 'b4190604': 1198,
 'pobox': 5274,
 '7876150ppm': 624,
 'joys': 3874,
 'lifeis': 4120,
 'waking': 7368,
 'each': 2532,
 'daywith': 2210,
 'thoughts': 6878,
 'somewheresomeone': 6320,
 'cares': 1685,
 'enough': 2639,
 'tosend': 6998,
 'warm': 7396,
 'morning': 4602,
 'greeting': 3262,
 'they': 6852,
 'said': 5888,
 'haf': 3314,
 'passport': 5117,
 'smth': 6278,
 'like': 4129,
 'dat': 2198,
 'juz': 3897,
 'send': 6016,
 'email': 2601,
 'account': 789,
 'wait': 7363,
 'freemsg': 3022,
 'hey': 3444,
 'darling': 2194,
 'been': 1306,
 'week': 7451,
 'word': 7600,
 'back': 1213,
 'fun': 3066,
 'still': 6493,
 'tb': 6739,
 'ok': 4935,
 'xxx': 7667,
 'std': 6472,
 'chgs': 1798,
 'rcv': 5595,
 '09061749602': 200,
 'from': 3050,
 'landline': 4020,
 'complimentary': 1961,
 'tenerife': 6781,
 'holiday': 3493,
 'await': 1181,
 'collection': 1917,
 'sae': 5881,
 'cs': 2115,
 'box': 1472,
 '528': 547,
 'hp20': 3551,
 '1yf': 347,
 '150ppm': 312,
 '18': 324,
 'ball': 1226,
 'moving': 4623,
 'will': 7531,
 'spin': 6393,
 'last': 4039,
 'very': 7283,
 'difficult': 2349,
 'bat': 1261,
 'stuff': 6552,
 'sell': 6009,
 'tell': 6767,
 'really': 5618,
 'able': 762,
 'friday': 3032,
 'hope': 3513,
 'can': 1650,
 'find': 2885,
 'alternative': 936,
 'yr': 7729,
 'term': 6784,
 'going': 3194,
 'rose': 5830,
 'red': 5655,
 'blood': 1412,
 'heart': 3403,
 'tis': 6923,
 'ur': 7209,
 'including': 3667,
 'poor': 5313,
 'relation': 5680,
 'support': 6627,
 'frnd': 3042,
 'many': 4369,
 'some1': 6308,
 'luvs': 4285,
 'praying': 5377,
 'god': 3188,
 'marry': 4385,
 'try': 7067,
 'she': 6083,
 'should': 6128,
 'quite': 5544,
 'diff': 2344,
 'guess': 3288,
 'rite': 5802,
 'turning': 7091,
 'off': 4913,
 'phone': 5197,
 'moms': 4581,
 'telling': 6768,
 'everyone': 2704,
 'cancer': 1657,
 'sister': 6196,
 'calling': 1638,
 'hurts': 3585,
 'talk': 6709,
 'put': 5517,
 'with': 7558,
 'see': 5990,
 'home': 3498,
 'cant': 1662,
 'take': 6702,
 'right': 5785,
 'happens': 3352,
 '2waxsto': 416,
 'wat': 7411,
 'want': 7389,
 'ill': 3634,
 'her': 3433,
 'medical': 4441,
 'insurance': 3718,
 'deliver': 2266,
 'basic': 1256,
 'currently': 2144,
 'shopping': 6119,
 'give': 3167,
 'til': 6908,
 'thats': 6829,
 'major': 4344,
 'person': 5175,
 'guide': 3294,
 'romcapspam': 5822,
 'around': 1081,
 'responding': 5747,
 'well': 7466,
 'presence': 5397,
 'since': 6181,
 'outgoing': 5033,
 'bringing': 1526,
 'real': 5609,
 'breath': 1512,
 'sunshine': 6616,
 'place': 5239,
 'points': 5293,
 'cultures': 2136,
 'module': 4573,
 'free': 3015,
 'video': 7292,
 'camera': 1647,
 'phones': 5201,
 'half': 3323,
 'price': 5413,
 'line': 4143,
 'rental': 5707,
 '12': 282,
 'mths': 4642,
 '500': 532,
 'cross': 2106,
 'ntwk': 4869,
 '100': 259,
 'txts': 7110,
 'mobileupd8': 4563,
 '08001950382': 48,
 'call2optout': 1628,
 '674': 582,
 'al': 902,
 'he': 3387,
 'does': 2416,
 'moan': 4557,
 'thin': 6856,
 'goes': 3190,
 'wrong': 7638,
 'its': 3778,
 'fault': 2821,
 'de': 2214,
 'arguments': 1070,
 'fed': 2833,
 'him': 3458,
 'himso': 3460,
 'bother': 1462,
 'hav': 3376,
 '2go': 390,
 'thanx': 6824,
 'xx': 7665,
 'yes': 7699,
 'small': 6251,
 'kid': 3948,
 'boost': 1449,
 'energy': 2624,
 'has': 3366,
 'bought': 1465,
 'ron': 5823,
 'present': 5398,
 'swatch': 6657,
 'watch': 7412,
 'entry': 2651,
 'into': 3731,
 '250': 369,
 'weekly': 7455,
 'comp': 1944,
 'win': 7534,
 '80086': 640,
 'www': 7652,
 'txttowin': 7113,
 'co': 1890,
 'uk': 7130,
 'cool': 2028,
 'tyler': 7114,
 're': 5598,
 'gonna': 3204,
 'buy': 1599,
 'drop': 2494,
 'his': 3464,
 'tonight': 6976,
 'total': 7002,
 'order': 5000,
 'quarter': 5532,
 'chance': 1742,
 'search': 5974,
 'hard': 3358,
 'let': 4102,
 'thanks': 6819,
 'am': 943,
 'doing': 2431,
 'torch': 6995,
 'bold': 1431,
 'im': 3636,
 'snowboarding': 6291,
 'trip': 7047,
 'wondering': 7591,
 'planning': 5248,
 'together': 6952,
 'befor': 1309,
 'go': 3183,
 'meet': 4444,
 'greet': 3261,
 'kind': 3958,
 'affair': 847,
 'cheers': 1784,
 'ain': 888,
 'answerin': 993,
 'actually': 812,
 'pretty': 5407,
 'reasonable': 5623,
 'hour': 3538,
 'sleepy': 6233,
 'kothi': 3990,
 'print': 5421,
 'marandratha': 4374,
 'splashmobile': 6400,
 'choose': 1827,
 '1000s': 262,
 'gr8': 3232,
 'tones': 6971,
 'wk': 7567,
 'subscrition': 6575,
 'service': 6037,
 'costing': 2047,
 '300p': 426,
 'credit': 2094,
 'kick': 3944,
 'mu': 4647,
 'figure': 2867,
 'money': 4585,
 'gas': 3105,
 'jay': 3816,
 'trying': 7069,
 'budget': 1565,
 'tough': 7007,
 'optimistic': 4988,
 'things': 6858,
 'improve': 3656,
 'nope': 4832,
 'ayo': 1195,
 'travelled': 7034,
 'forgotten': 2983,
 'guy': 3302,
 'dirty': 2368,
 'fellow': 2843,
 'waqt': 7395,
 'se': 5972,
 'pehle': 5148,
 'naseeb': 4715,
 'zyada': 7751,
 'kisi': 3966,
 'ko': 3984,
 'kuch': 3993,
 'nahi': 4697,
 'milta': 4502,
 'zindgi': 7748,
 'wo': 7580,
 'jo': 3848,
 'hum': 3570,
 'sochte': 6296,
 'hai': 3317,
 'ham': 3328,
 'jeetey': 3825,
 'baby': 1208,
 'stretch': 6527,
 'open': 4973,
 'pussy': 5516,
 'any': 1002,
 'opening': 4975,
 'mca': 4423,
 'congratulations': 1988,
 'either': 2584,
 'cd': 1717,
 'gift': 3154,
 'vouchers': 7338,
 'draw': 2475,
 'txt': 7104,
 'music': 4672,
 '87066': 690,
 'tncs': 6943,
 'ldew': 4064,
 'com': 1924,
 'win150ppmx3age16': 7535,
 'ho': 3484,
 'big': 1360,
 'belly': 1327,
 'laugh': 4049,
 'ya': 7676,
 'tomo': 6966,
 'oh': 4930,
 'why': 7514,
 'job': 3850,
 'whats': 7489,
 'yup': 7739,
 'leh': 4089,
 'sent': 6025,
 'town': 7010,
 'mrt': 4629,
 'down': 2462,
 'ad': 813,
 'crap': 2082,
 'nite': 4804,
 'borin': 1454,
 'without': 7561,
 'boggy': 1429,
 'boring': 1455,
 'biatch': 1357,
 'nxt': 4887,
 'il': 3633,
 'ave': 1173,
 'house': 3541,
 'maid': 4336,
 'murderer': 4668,
 'coz': 2074,
 'man': 4353,
 'murdered': 4667,
 'th': 6814,
 'january': 3809,
 'as': 1098,
 'public': 5492,
 'govt': 3230,
 'instituitions': 3716,
 'closed': 1871,
 'post': 5336,
 'office': 4920,
 'understand': 7155,
 'todays': 6949,
 'shows': 6142,
 '2000': 350,
 'guaranteed': 3283,
 '09066358361': 224,
 'land': 4019,
 'claim': 1844,
 'y87': 7675,
 'valid': 7251,
 '12hrs': 292,
 'only': 4963,
 'told': 6959,
 'name': 4702,
 'gautham': 3108,
 'ah': 878,
 'deep': 2243,
 'sigh': 6160,
 'miss': 4530,
 'surprised': 6640,
 'haven': 3379,
 'gone': 3202,
 'net': 4761,
 'cafe': 1617,
 'yet': 7702,
 'don': 2439,
 'good': 3206,
 'weekend': 7453,
 'ps': 5482,
 'grown': 3275,
 'registered': 5674,
 'sinco': 6182,
 'payee': 5134,
 'log': 4195,
 'icicibank': 3607,
 'enter': 2641,
 'urn': 7221,
 'confirm': 1980,
 'beware': 1349,
 'frauds': 3009,
 'share': 6076,
 'disclose': 2376,
 'anyone': 1005,
 'headache': 3389,
 'use': 7227,
 'sick': 6157,
 'rt': 5845,
 'king': 3961,
 'pro': 5433,
 'club': 1878,
 'help': 3422,
 'info': 3690,
 'ringtoneking': 5795,
 '08701237397': 69,
 'must': 4675,
 '16': 319,
 'credits': 2096,
 'redeemable': 5656,
 'about': 763,
 'clothes': 1875,
 'jewelry': 3840,
 'trips': 7049,
 'watching': 7415,
 'surya': 6644,
 'movie': 4620,
 'after': 859,
 'pm': 5271,
 'vijay': 7299,
 'pokkiri': 5296,
 'once': 4955,
 'plus': 5268,
 'grinule': 3266,
 'whenever': 7494,
 'speak': 6370,
 'huh': 3567,
 'late': 4042,
 'fr': 3003,
 'fret': 3030,
 'ovulation': 5049,
 'test': 6795,
 'strips': 6534,
 'wont': 7593,
 'march': 4375,
 'postal': 5337,
 'address': 821,
 'alright': 932,
 'okay': 4936,
 'unique': 7170,
 '30th': 431,
 'august': 1157,
 'areyouunique': 1064,
 'were': 7474,
 'hill': 3455,
 'thing': 6857,
 'hiya': 3471,
 'probably': 5435,
 'coming': 1935,
 'next': 4780,
 'plz': 5270,
 'note': 4846,
 'amp': 958,
 'asks': 1113,
 'type': 7115,
 'disconnect': 2377,
 'iz': 3787,
 'terrorist': 6791,
 'make': 4345,
 'sim': 6174,
 'card': 1673,
 'itz': 3781,
 'confirmd': 1981,
 'by': 1610,
 'nokia': 4820,
 'motorola': 4613,
 'verified': 7278,
 'cnn': 1888,
 'ibn': 3601,
 'custom': 2150,
 'officer': 4921,
 'discount': 2379,
 'number': 4874,
 'coveragd': 2072,
 'area': 1060,
 'urgnt': 7216,
 'vasai': 7262,
 'reach': 5599,
 'before': 1310,
 'clock': 1867,
 '447801259231': 496,
 '09058094597': 178,
 'mmmmmm': 4550,
 'ahmad': 883,
 'year': 7689,
 'begin': 1315,
 'every': 2699,
 'second': 5979,
 'closer': 1872,
 'being': 1322,
 'side': 6159,
 'happy': 3357,
 'new': 4772,
 'training': 7019,
 'manual': 4368,
 'show': 6135,
 'tech': 6756,
 'process': 5442,
 'password': 5118,
 'reset': 5739,
 'troubleshooting': 7055,
 'madam': 4321,
 'regret': 5676,
 'disturbance': 2391,
 'might': 4494,
 'receive': 5634,
 'reference': 5660,
 'check': 1774,
 'dlf': 2402,
 'premarica': 5387,
 'kindly': 3960,
 'informed': 3693,
 'rgds': 5776,
 'rakhesh': 5569,
 'kerala': 3932,
 'says': 5938,
 'old': 4944,
 'waiting': 7366,
 'pete': 5185,
 'please': 5260,
 'ring': 5791,
 'meive': 4453,
 'hardly': 3361,
 'gotany': 3224,
 'way': 7425,
 'haha': 3315,
 'heard': 3400,
 'text': 6801,
 'inside': 3708,
 'da': 2168,
 'park': 5101,
 'si': 6153,
 'como': 1943,
 'listened2the': 4163,
 'plaid': 5242,
 'album': 906,
 'gd': 3119,
 'air1': 891,
 'which': 7502,
 'hilarious': 3454,
 'also': 934,
 'boughtåóbraindanceåóa': 1466,
 'ofstuff': 4926,
 'aphexåõs': 1021,
 'abel': 756,
 'sipix': 6191,
 'digital': 2352,
 '09061221061': 189,
 'delivery': 2269,
 'within': 7560,
 '28days': 378,
 'box177': 1473,
 'm221bp': 4295,
 '2yr': 419,
 'warranty': 7401,
 'på': 5524,
 '99': 736,
 'yahoo': 7678,
 'photos': 5204,
 'yesterday': 7701,
 'flood': 2933,
 'cum': 2137,
 'dude': 2511,
 'longer': 4210,
 'pisces': 5230,
 'aquarius': 1052,
 'pick': 5211,
 'tuesday': 7081,
 'evening': 2693,
 'lacking': 4007,
 'most': 4606,
 'particular': 5105,
 'dramastorm': 2472,
 'details': 2306,
 'part': 5104,
 'worried': 7612,
 'case': 1696,
 'wake': 7367,
 'forgot': 2982,
 'something': 6315,
 'grandma': 3243,
 'today': 6948,
 'parade': 5090,
 'bit': 1381,
 'wishing': 7554,
 'family': 2798,
 'merry': 4473,
 'mas': 4389,
 'advance': 838,
 'coulda': 2056,
 'valentine': 7249,
 'wasn': 7405,
 'never': 4770,
 'nothing': 4850,
 'yar': 7682,
 'lor': 4223,
 'wan': 7384,
 'horse': 3525,
 'racing': 5554,
 'mah': 4332,
 'eat': 2548,
 'earlier': 2535,
 'ate': 1132,
 'chicken': 1801,
 'rice': 5780,
 'guoyang': 3299,
 'propose': 5470,
 'again': 866,
 'tomorrow': 6968,
 '09050001295': 162,
 'a21': 745,
 'block': 1405,
 'breaker': 1508,
 'comes': 1931,
 'deluxe': 2271,
 'format': 2986,
 'features': 2830,
 'graphics': 3246,
 'replying': 5720,
 'bbdeluxe': 1275,
 'challenge': 1737,
 'finally': 2882,
 'lunch': 4278,
 'knw': 3983,
 'vl': 7324,
 'giv': 3166,
 'kano': 3912,
 'anyway': 1013,
 'wit': 7557,
 '1st': 339,
 'salary': 5891,
 'izzit': 3788,
 'raining': 5562,
 'list': 4160,
 'buyers': 1601,
 'system': 6683,
 'sh': 6058,
 'ready': 5608,
 'missing': 4534,
 'pray': 5375,
 'inshah': 3707,
 'allah': 919,
 'ard': 1058,
 'realise': 5611,
 'exams': 2725,
 'outta': 5039,
 'day': 2207,
 'coffee': 1901,
 'cake': 1619,
 'subscribed': 6569,
 'best': 1339,
 'days': 2208,
 'until': 7191,
 '82324': 656,
 'helpline': 3427,
 '08706091795': 81,
 'afternoon': 861,
 'woke': 7582,
 'early': 2537,
 'online': 4961,
 'hmmm': 3478,
 'italian': 3773,
 'boy': 1487,
 'grins': 3265,
 'pa': 5060,
 'dont': 2443,
 'ru': 5847,
 'smile': 6262,
 'hppnss': 3552,
 'tear': 6752,
 'sorrow': 6337,
 'mine': 4508,
 'wil': 7527,
 'forevr': 2975,
 'goodfriend': 3208,
 'picking': 5213,
 'us': 7223,
 'taking': 6707,
 'sq825': 6429,
 'reaching': 5601,
 'arrival': 1087,
 'soon': 6330,
 'oic': 4932,
 'sis': 6195,
 'dad': 2172,
 'went': 7471,
 'dunno': 2519,
 'whether': 7501,
 'sch': 5945,
 'asked': 1110,
 'sen': 6015,
 'chennai': 1789,
 'absolutely': 767,
 'south': 6356,
 'recently': 5639,
 'started': 6457,
 'http': 3558,
 'tms': 6940,
 'widelive': 7520,
 'index': 3679,
 'wml': 7576,
 'id': 3611,
 '820554ad0a1705572711': 653,
 'trueåác': 7060,
 'ringtoneåá': 5797,
 'idea': 3613,
 'converted': 2017,
 'live': 4170,
 'angry': 976,
 'aft': 858,
 'here': 3434,
 'tv': 7094,
 'available': 1169,
 'work': 7602,
 'vivek': 7323,
 'didn': 2335,
 'tiime': 6907,
 'hug': 3562,
 'break': 1507,
 'tears': 6753,
 'studying': 6550,
 'vodafone': 7326,
 'numbers': 4875,
 'ending': 2618,
 '4882': 507,
 'selected': 6003,
 '350': 443,
 'award': 1184,
 'matches': 4399,
 '09064019014': 213,
 'friendship': 3038,
 'game': 3091,
 'play': 5252,
 'doesn': 2418,
 'start': 6456,
 'ends': 2621,
 'may': 4419,
 'believe': 1323,
 'true': 7058,
 'incredible': 3673,
 'learn': 4073,
 'truly': 7062,
 'amazing': 944,
 'blow': 1415,
 'mind': 4505,
 'o2fwd': 4894,
 '18p': 327,
 'over': 5042,
 'whatever': 7488,
 'captain': 1670,
 'vijaykanth': 7300,
 'comedy': 1930,
 'drunken': 2503,
 'mr': 4626,
 'sheffield': 6085,
 'wanna': 7387,
 'boss': 1458,
 'nanny': 4711,
 'raise': 5563,
 'ringtone': 5794,
 '1b6a5ecef91ff9': 331,
 '37819': 451,
 'true18': 7059,
 '0430': 15,
 'jul': 3882,
 '05': 16,
 'iam': 3596,
 'sleep': 6227,
 'fetch': 2848,
 ...}

In [59]:
x_train_np= x_train_cv.toarray()
x_train_np

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4457, 7767))

In [60]:
np.where(x_train_np[0]!=0)

(array([ 907,  970,  988, 1824, 4591, 4745, 7450]),)

In [61]:
x_train[0:4]

979     Another month. I need chocolate weed and alcohol.
3014     &lt;#&gt;  mins but i had to stop somewhere f...
3259    I'm always looking for an excuse to be in the ...
1743                     I love to wine and dine my lady!
Name: v2, dtype: str

In [68]:
#### Naive Bayes classifier
model =MultinomialNB()
model.fit(x_train_cv, y_train)

MultinomialNB()

In [70]:
y_pred= model. predict(x_test_cv)

In [74]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       994
           1       0.98      0.93      0.96       121

    accuracy                           0.99      1115
   macro avg       0.99      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115

### Test On a random dataset

In [83]:
message=("50% off")

In [87]:
message_cnt= v.transform([message])
model.predict(message_cnt)

array([0])